# Generated by Django 5.1.2 on 2024-10-31 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_listitem_completion_time_listitem_delay'),
        ('todo', '0002_listitem_priority'),
    ]

    operations = [
    ]
