# Generated by Django 5.1.2 on 2024-11-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_template_due_date_alter_listitem_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
