name: Django CI

on:
  push:
    branches: [ "vatsal" ]
  pull_request:
    branches: [ "vatsal" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.6
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run manage.py test
        coverage lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/coverage.lcov
        parallel: true

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
        parallel-finished: true
